### ISSUE TITLE
Add mempool policy/DoS protection.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-blockchain#107]

**Comment by RojavaCrypto** [comment]
mempool policy should be changeable by providing alternative callbacks for miners. I personally would accept transactions based on memory available, with higher fee transactions pushing out lower fee ones.

**Comment by evoskuil** [comment]
The plan for v3 mempool policy is an abbreviated version of the objective for v4. The following settings are in place to allow for tradeoff between DOS protection and maximization of fee potential.
```ini
[node]
# The minimum fee required for transaction acceptance, defaults to 1.
minimum_fee_satoshis = 1
# Retain only the first seen of conflicting transactions, defaults to true.
reject_conflicts = true
# Request that peers relay transactions, defaults to true.
relay_transactions = true
# Request transactions on each channel start, defaults to true.
refresh_transactions = true
```
#### minimum_fee_satoshis 
This policy is applied to transactions individually (i.e. independent of fee maximizations - i.e. CPFP).

A zero fee policy would result in zero cost to exceed the storage capability of the node. Any policy based based on size would fail under a zero fee policy as free transactions could push out all others. Age expiration would have no effect on this problem. 1 satoshi is a placeholder for a more substantial fee, but it is the absolute minimum rational policy regardless of purchasing power changes. Nevertheless, a zero fee configuration is honored (but is not the default).

#### reject_conflicts
If set this will reject any transaction that spends an output that is spent by another transaction already in the pool (or in the chain). Block pool transactions should be moved into the pool (retaining only headers and hash lists in block pool) so these should be considered included as well.

If not set this will allow any number of conflicts to coexist in the transaction pool, including those against outputs that are spent by a depth that does not exceed the reorg limit (as reorg could free up those transactions). Combining with an unlimited reorganization capability would result in all (apart from double spent) txs being accepted (and retained indefinitely).  This setting is insufficient for DOS and as such should only be used under other external protections as an attacker can overflow the storage of the node at the cost of a single tx minimum fee.

#### relay_transactions
Request that peers relay transactions, defaults to true. This allows the node to operate without a transaction pool if so desired. Peers that violate the policy are dropped.

#### refresh_transactions
Request transactions on each channel start, defaults to true. This primes the memory pool using the `mempool` message.

**Comment by evoskuil** [comment]
This is implemented with the exception of `reject_conflicts`.
