### ISSUE TITLE
Verified block infinite loop

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-blockchain#167]
Quick question. I got into a state where it just infinitely verifies the same block and never moves forward. Is this a corrupt database issue in general?

**Comment by evoskuil** [comment]
Were you fully synced with block pool set to 1?

**Comment by hoffmabc** [comment]
Yes.

**Comment by evoskuil** [comment]
Please see: https://github.com/libbitcoin/libbitcoin-server/wiki/Configuration-Settings#default-settings

I'm dealing with this in 3.0. The changes to fix version2 sync were a patch measure to get sync working well, but the transition from sync requires manual config. You are hung up on a single block reorg.

**Comment by evoskuil** [comment]
Tracking: https://github.com/libbitcoin/libbitcoin-server/issues

**Comment by hoffmabc** [comment]
Ok I had it happen to my other node. 

```
17:50:14.956692 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.956725 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.960359 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.960400 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.963823 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.963856 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.967464 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.967504 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.971076 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.971112 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.974795 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.974829 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
17:50:14.978742 INFO [blockchain] Block [727792] verify (1) txs and (1) inputs
17:50:14.978775 INFO [blockchain] Block [727792] verified in (0) secs or (0) ms/input
ZAUTH I: ALLOWED (NULL)
ZAUTH I: ALLOWED (NULL)
```

**Comment by evoskuil** [comment]
I don't follow, is this a cross-post of the server cert issue?

**Comment by evoskuil** [comment]
Is the other node configured in the same manner?

**Comment by hoffmabc** [comment]
No it's not a crosspost. Sorry the ZAUTH just snuck in the log. Anyways it's good to go now with Block Pool bumped to 20.

**Comment by hoffmabc** [comment]
It's catching up quickly now.

**Comment by evoskuil** [comment]
Okay, yeah - I posted too quickly. Thanks for all of the feedback!

**Comment by hoffmabc** [comment]
No worries. Thanks for posting that before I blew away the 2nd database :)
