### ISSUE TITLE
Mac OSX Build Error/Issue

### ISSUE THREAD

**Issue by skaht** [libbitcoin/libbitcoin-blockchain#50]
Here are the results of a serialized makefile output:
.
.
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-blockchain.pc
config.status: executing depfiles commands
config.status: executing libtool commands
  CXX      src/libbitcoin_blockchain_la-blockchain.lo
  CXX      src/libbitcoin_blockchain_la-checkpoints.lo
  CXX      src/libbitcoin_blockchain_la-transaction_pool.lo
  CXX      src/libbitcoin_blockchain_la-validate.lo
  CXX      src/libbitcoin_blockchain_la-organizer.lo
In file included from ../libbitcoin-blockchain/src/organizer.cpp:20:
../libbitcoin-blockchain/include/bitcoin/blockchain/organizer.hpp:104:43: error: no member named 'max_size_t' in namespace 'libbitcoin'; did you mean
      'vm_size_t'?
    static constexpr size_t null_height = bc::max_size_t;
                                          ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/mach/i386/vm_types.h:112:20: note: 
      'vm_size_t' declared here
typedef uintptr_t               vm_size_t;
                                ^
1 error generated.
make: *** [src/libbitcoin_blockchain_la-organizer.lo] Error 1

Any recommendations?

**Comment by evoskuil** [comment]
Did you run the build script [install.sh](https://github.com/evoskuil/libbitcoin-blockchain/blob/master/install.sh) or are you building manually? If the latter then please make sure you have the dependencies correct, in this case libbitcoin looks out of date. You can see [here](https://github.com/evoskuil/libbitcoin/blob/master/include/bitcoin/bitcoin/constants.hpp#L88) that the constant in question is defined.

**Comment by skaht** [comment]
You are correct, my constants.hpp file from libbitcoin was the culprit that was missing the CPP section enshrining the “max_size_t”, visible at https://github.com/evoskuil/libbitcoin/blob/master/include/bitcoin/bitcoin/constants.hpp#L88 <https://github.com/libbitcoin/libbitcoin-blockchain/blob/master/Makefile.am> :-) Never would have figured that out…  
Used "git checkout v2.7.0”.  Now using "git checkout master” or the HEAD fixed the issue.

Got libbitcoin-blockchain to fully compile and link:-) Here’s the romancing of the GNU configure script that got me rolling:

../$package/configure \
--prefix=$libbitcoin_blockchain_dir \
CPPFLAGS="-I$boost_dir/include" \
LDFLAGS="-L$boost_dir/lib -L$libbitcoin_dir/lib" \
--with-boost=$boost_dir \
bitcoin_CFLAGS=-I$libbitcoin_dir/include \
bitcoin_LIBS=-lbitcoin \
--without-tests

FYSA, when I used

PKG_CONFIG_PATH=$libbitcoin_dir/lib/pkgconfig

got complaints about 'libbitcoin >= 2.8.0' but version of libbitcoin is 2.7.0
However, no 2.8.0 git configuration existed that I could obtain

Thanks again. I’m off to getting LibBitcoin-Node to build next.

Cheers,

Scott

**Comment by evoskuil** [comment]
libbitocin-blockchain expects libbitcoin/version2, which is 2.8.0. Again, I recommend the install.sh for each repo. At a minimum you can use it to determine the proper configuration. It supports prefix and does not require sudo. If you are trying to build -server then just start there and it will be all laid out for you.
