### ISSUE TITLE
32 bits compatibility?

### ISSUE THREAD

**Issue by PabloCastellano** [libbitcoin/libbitcoin-blockchain#67]
During my attempt to generate a debian package of libbitcoin-blockchain for i386 I discovered the following assert in src/database/mmfile.cpp:

```
// mmfile should be able to support 32 bit but because the blockchain 
// requires a larger file this is not validated or supported.
static_assert(sizeof(void*) == sizeof(uint64_t), "Not a 64 bit system!");
```

Just to know, isn't there any plan or trick at all to support 32bits?

**Comment by evoskuil** [comment]
I'm pretty sure that if the assertion is removed it will build. However libbitcoin-blockchain is a hash table and the size of the Bitcoin blockchain requires more than 32 bits for indexing its data. So blockchain is not supportable on 32 bit platforms without some pretty significant surgery.
